name: HerLife Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m pytest
    - name: Run linter
      run: |
        python -m flake8
    - name: Run mypy
      run: |
        python -m mypy .
    - name: Run black
      run: |
        python -m black --check .
    - name: Run isort
      run: |
        python -m isort --check .